---
ID: "bf4243e6-daa2-49dd-a4ce-6369b804d8bb"
Parent: "de5d8569-916b-472a-aebf-4c61ad4c0922"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: "/sitecore/templates/Project/midnighteffort/JSS Settings"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/document_template.png
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "JSS Settings"
